<a href="https://colab.research.google.com/github/asaito2001/Curso_python_Alura_IA_Aplicada/blob/master/05_Conhecendo_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Prompt para gerar um dataframe com 50 registros
'''
Crie um dataframe com o pandas com 5 colunas:
 - Primeira coluna produto
 - Segunda coluna categoria do produto
 - Terceira coluna preço do produto
 - Quarta coluna avaliação do produto( de 1.0 a 5.0)
 - Quinta coluna quantidade vendida Gerar 50 linhas para cada uma
   dessas colunas
'''

'\nCrie um dataframe com o pandas com 5 colunas:\n - Primeira coluna produto\n - Segunda coluna categoria do produto\n - Terceira coluna preço do produto\n - Quarta coluna avaliação do produto( de 1.0 a 5.0) \n - Quinta coluna quantidade vendida Gerar 50 linhas para cada uma \n   dessas colunas\n'

In [ ]:
import pandas as pd
import numpy as np

# Gerar 50 linhas de dados para cada coluna
num_rows = 50

# Coluna 'produto'
produtos = [
    'Notebook', 'Smartphone', 'Smart TV', 'Fones de Ouvido', 'Teclado Mecânico',
    'Mouse Gamer', 'Monitor UltraWide', 'Câmera Digital', 'Console de Videogame', 'Tablet',
    'Impressora', 'Roteador Wi-Fi', 'Caixa de Som Bluetooth', 'Webcam HD', 'Microfone USB',
    'Disco Rígido Externo', 'SSD Interno', 'Placa de Vídeo', 'Memória RAM', 'Processador',
    'Fonte de Alimentação', 'Gabinete Gamer', 'Placa Mãe', 'Cooler para CPU', 'Mouse Pad',
    'Mochila para Notebook', 'Carregador Portátil', 'Smartwatch', 'Bateria Externa', 'Cabo HDMI',
    'Adaptador USB-C', 'Controle de Videogame', 'Fone Bluetooth', 'Drone', 'Cadeira Gamer',
    'Óculos de Realidade Virtual', 'Tripé para Câmera', 'Anel de Luz LED', 'Lâmpada Inteligente', 'Tomada Inteligente',
    'Sensor de Porta/Janela', 'Fechadura Eletrônica', 'Termostato Inteligente', 'Assistente Virtual', 'Fone com Fio',
    'Mouse Sem Fio', 'Teclado Sem Fio', 'Pen Drive', 'Cartão de Memória', 'Leitor de Cartões'
]
produto_data = np.random.choice(produtos, num_rows, replace=True)

# Coluna 'categoria do produto'
categorias = [
    'Eletrônicos', 'Informática', 'Acessórios', 'Games', 'Automação Residencial',
    'Áudio', 'Fotografia', 'Periféricos', 'Armazenamento', 'Componentes'
]
categoria_data = np.random.choice(categorias, num_rows, replace=True)

# Coluna 'preço do produto'
preco_data = np.round(np.random.uniform(50.00, 5000.00, num_rows), 2)

# Coluna 'avaliação do produto'
avaliacao_data = np.round(np.random.uniform(1.0, 5.0, num_rows), 1)

# Coluna 'quantidade vendida'
quantidade_data = np.random.randint(1, 1000, num_rows)

# Criar o DataFrame
df = pd.DataFrame({
    'produto': produto_data,
    'categoria_do_produto': categoria_data,
    'preco_do_produto': preco_data,
    'avaliacao_do_produto': avaliacao_data,
    'quantidade_vendida': quantidade_data
})

# Exibir as primeiras 5 linhas do DataFrame
display(df.head())

,produto,categoria_do_produto,preco_do_produto,avaliacao_do_produto,quantidade_vendida
0,Mouse Gamer,Periféricos,3662.17,2.1,530
1,Teclado Sem Fio,Periféricos,122.02,2.6,542
2,SSD Interno,Games,4080.77,3.6,854
3,Bateria Externa,Informática,2332.46,3.6,683
4,Termostato Inteligente,Automação Residencial,2122.81,2.8,446

In [ ]:
# Exibindo as primeiras linhas do Dataframe
display(df.head())

,produto,categoria_do_produto,preco_do_produto,avaliacao_do_produto,quantidade_vendida
0,Mouse Gamer,Periféricos,3662.17,2.1,530
1,Teclado Sem Fio,Periféricos,122.02,2.6,542
2,SSD Interno,Games,4080.77,3.6,854
3,Bateria Externa,Informática,2332.46,3.6,683
4,Termostato Inteligente,Automação Residencial,2122.81,2.8,446

In [ ]:
# Exibindo as últimas linhas do Dataframe
display(df.tail())

,produto,categoria_do_produto,preco_do_produto,avaliacao_do_produto,quantidade_vendida
45,Mouse Gamer,Armazenamento,762.59,4.2,314
46,Cadeira Gamer,Eletrônicos,829.36,2.7,122
47,Tablet,Áudio,1729.58,4.5,542
48,Pen Drive,Fotografia,2227.17,1.7,500
49,SSD Interno,Armazenamento,3114.75,4.0,66

In [ ]:
# Exibindo dados únicos de categorias - devolve um array
df['categoria_do_produto'].unique()

array(['Periféricos', 'Games', 'Informática', 'Automação Residencial',
       'Componentes', 'Áudio', 'Armazenamento', 'Acessórios',
       'Eletrônicos', 'Fotografia'], dtype=object)

In [ ]:
# Exibindo dados únicos de categorias com outra opção - devolve um dict
set(df['categoria_do_produto'])

{'Acessórios',
 'Armazenamento',
 'Automação Residencial',
 'Componentes',
 'Eletrônicos',
 'Fotografia',
 'Games',
 'Informática',
 'Periféricos',
 'Áudio'}

## Filtrando elementos de um Dataframe Pandas

In [ ]:
df[df['categoria_do_produto'] == 'Eletrônicos']

,produto,categoria_do_produto,preco_do_produto,avaliacao_do_produto,quantidade_vendida
11,Tablet,Eletrônicos,2834.30,4.9,760
15,Monitor UltraWide,Eletrônicos,2626.75,1.6,786
29,Termostato Inteligente,Eletrônicos,3784.13,4.4,670
36,Pen Drive,Eletrônicos,4940.47,1.9,873
37,Assistente Virtual,Eletrônicos,4204.78,1.7,217
38,Gabinete Gamer,Eletrônicos,3653.40,4.9,447
46,Cadeira Gamer,Eletrônicos,829.36,2.7,122

In [ ]:
df[df['avaliacao_do_produto'] < 2.0]

,produto,categoria_do_produto,preco_do_produto,avaliacao_do_produto,quantidade_vendida
8,Teclado Mecânico,Periféricos,2246.69,1.3,127
10,Fone com Fio,Acessórios,3571.61,1.9,109
13,Adaptador USB-C,Periféricos,1267.46,1.9,633
14,Placa Mãe,Periféricos,1500.88,1.1,381
15,Monitor UltraWide,Eletrônicos,2626.75,1.6,786
25,Teclado Sem Fio,Armazenamento,2287.69,1.4,795
28,Smartphone,Acessórios,3165.26,1.2,195
30,Controle de Videogame,Games,2649.46,1.1,707
36,Pen Drive,Eletrônicos,4940.47,1.9,873
37,Assistente Virtual,Eletrônicos,4204.78,1.7,217
41,Teclado Mecânico,Fotografia,439.93,1.5,620
43,Adaptador USB-C,Informática,4405.66,1.8,432
48,Pen Drive,Fotografia,2227.17,1.7,500

In [ ]:
df[(df['categoria_do_produto'] == 'Eletrônicos') & (df['preco_do_produto'] >= 1200.00)]

,produto,categoria_do_produto,preco_do_produto,avaliacao_do_produto,quantidade_vendida
11,Tablet,Eletrônicos,2834.30,4.9,760
15,Monitor UltraWide,Eletrônicos,2626.75,1.6,786
29,Termostato Inteligente,Eletrônicos,3784.13,4.4,670
36,Pen Drive,Eletrônicos,4940.47,1.9,873
37,Assistente Virtual,Eletrônicos,4204.78,1.7,217
38,Gabinete Gamer,Eletrônicos,3653.40,4.9,447

### Utilizando LOC e ILOC

In [ ]:
# ILOC pega o registro pelo indice
df.iloc[15]

produto                 Monitor UltraWide
categoria_do_produto          Eletrônicos
preco_do_produto                  2626.75
avaliacao_do_produto                  1.6
quantidade_vendida                    786
Name: 15, dtype: object

In [ ]:
df.iloc[15:40]

,produto,categoria_do_produto,preco_do_produto,avaliacao_do_produto,quantidade_vendida
15,Monitor UltraWide,Eletrônicos,2626.75,1.6,786
16,Mochila para Notebook,Componentes,2879.63,4.1,293
17,Fone com Fio,Acessórios,3164.52,3.7,521
18,Monitor UltraWide,Periféricos,1438.33,3.6,708
19,Adaptador USB-C,Componentes,3620.39,3.1,527
20,Smart TV,Componentes,3770.58,3.8,311
21,Carregador Portátil,Acessórios,1184.24,2.4,487
22,Mouse Pad,Automação Residencial,4746.64,3.2,874
23,Placa de Vídeo,Games,1141.88,2.5,988
24,Notebook,Armazenamento,4509.80,3.7,773
25,Teclado Sem Fio,Armazenamento,2287.69,1.4,795
26,Gabinete Gamer,Áudio,2744.25,4.0,200
27,Microfone USB,Componentes,1211.06,4.9,257
28,Smartphone,Acessórios,3165.26,1.2,195
29,Termostato Inteligente,Eletrônicos,3784.13,4.4,670
30,Controle de Videogame,Games,2649.46,1.1,707
31,Anel de Luz LED,Fotografia,2423.93,2.3,452
32,Roteador Wi-Fi,Acessórios,749.71,2.4,21
33,Assistente Virtual,Componentes,481.97,3.8,26
34,Termostato Inteligente,Áudio,141.91,4.9,249
35,Câmera Digital,Armazenamento,2456.12,2.2,782
36,Pen Drive,Eletrônicos,4940.47,1.9,873
37,Assistente Virtual,Eletrônicos,4204.78,1.7,217
38,Gabinete Gamer,Eletrônicos,3653.40,4.9,447
39,Câmera Digital,Automação Residencial,505.58,4.2,138

# Desafio com python e pandas

1. Carregar um arquivo .csv com feedback de clientes (reviews.csv)
2. Usar um LLM para classificar o sentimento de cada feedback (Positivo, Negativo, Neutro)
3. Adicionar essa classificação ao Dataframe.

In [4]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.3/138.3 kB 5.0 MB/s eta 0:00:00

In [6]:
import os
from google.colab import userdata

os.environ['GROQ_API_KEY'] = userdata.get('GROQ_API_KEY')

In [7]:
from groq import Groq

client = Groq()

In [35]:
def resposta_sentimento_llm(review, model_llm='llama-3.3-70b-versatile'):

  response = client.chat.completions.create(
      model=model_llm,
      messages=[{'role': 'user', 'content': review}],
      temperature=0,
      max_completion_tokens=20,
      stream=False
  )

  return response.choices[0].message.content.strip()

### Few-shot-prompting

In [33]:
def classificar_sentimento(texto):

    prompt = f"""
Classifique o sentimento do texto abaixo.

Categorias possíveis:
Positivo, Negativo ou Neutro.

Exemplos:
'Eu adorei esse produto' -> 'Positivo'
'Gostei, mas não é nada de especial' -> 'Neutro'
'Odiei esse produto' -> 'Negativo'

Review a ser analisado: {texto}

Responda apenas com uma palavra.
"""

    try:
        resposta = resposta_sentimento_llm(prompt)

        if resposta not in ["Positivo", "Negativo", "Neutro"]:
            return "Indefinido"

        return resposta

    except Exception:
        return "Erro"

In [49]:
import pandas as pd

df = pd.read_csv('/content/reviews.csv')
df_review = df['reviewText']

In [51]:
lista_review_sentimento = []

for review_indice, review_texto in enumerate(df_review):
  sentimento = classificar_sentimento(review_texto)
  lista_review_sentimento.append(sentimento)

  #print(f'Idx review: {review_indice} | review: {review_texto} -> {sentimento}')

In [52]:
df['Sentimento'] = lista_review_sentimento

In [53]:
df.to_csv(
    "reviews_com_sentimentos.csv",
    index=False,
    sep=",",
    encoding="utf-8-sig"   # evita problema com acentos
)

print("CSV gerado com sucesso.")

CSV gerado com sucesso.

# set_index no pandas

In [54]:
# Exemplo simples: convertendo uma coluna para índice
import pandas as pd

dados = {'Produto': ['Produto A', 'Produto B', 'Produto C'],
         'Preço': [100, 150, 200],
         'Estoque': [30, 20, 50]}
df = pd.DataFrame(dados)

# Transformando a coluna 'Produto' em índice
df_indexado = df.set_index('Produto')
print(df_indexado)

           Preço  Estoque
Produto
Produto A    100       30
Produto B    150       20
Produto C    200       50